name: Build Crate and Docs

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-crate:
    name: Build crate on ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v6
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build crate
        run: cargo build --release --verbose

      - name: Build docs
        run: cargo doc --verbose

      - name: Publish dry run
        run: |
          cargo check --verbose
          cargo package --verbose
          cargo publish --dry-run --verbose
